// import { Geist, Geist_Mono } from "next/font/google";
import { MantineProvider } from "@mantine/core";
import "./globals.css";
import "@mantine/carousel/styles.css";
import NavBar from "@/components/nav-bar";
import Footer from "@/components/footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
// ${geistSans.variable} ${geistMono.variable}

export const metadata = {
  title: "SkillUp Academy 🏫",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased scroll-smooth`}>
        <NavBar />
        <MantineProvider>{children}</MantineProvider>
        <Footer />
      </body>
    </html>
  );
}
